

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      start:
        description: "Start time of mute_alert"
        required: true
        type: string
      end:
        description: "End time of mute_alert"
        required: true
        type: string
      dc:
        description: "Name of DC"
        required: true
        type: string

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-reusable-workflow:
    uses: rakesh2525/Practice/.github/workflows/blank.yml@main
    with:
      start: "'2025-05-16 10.35'"
     

   
