

name: CI

# Controls when the workflow will runs
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      start:
        description: "Start time of mute_alert"
        required: true
        type: string
      end:
        description: "End time of mute_alert"
        required: true
        type: string
      dc:
        description: "Name of DC"
        required: true
        type: string




jobs:
  call-blank:
    uses: rakesh2525/Practice/.github/workflows/blank.yml@main
    

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   Mute_Alerts:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           repository: rakesh2525/Practice
#           ref: main
#           path: cicd

#       - name: GitHub Context Debug
#         run: |
#           echo $JSON | jq
#         env:
#           JSON: ${{ toJSON(github) }}

#       - name: Run Mute Alerts Script
#         shell: bash
#         working-directory: cicd/devop/
#         run: |
#           # make run-script start=${{ github.event.inputs.start }} end=${{ github.event.inputs.end }} dc=${{ github.event.inputs.dc }}
#           chmod +x hi.sh
#           ./hi.sh
#           echo "start_Time=${{ github.event.inputs.start }}"
     

   
